### ISSUE TITLE
ApiKeys.list() output is always empty

### ISSUE THREAD

**Issue by mkucharz** [Syncano/syncano4-js#2]
Steps to repeat:

```
syncano.ApiKeys.create().then(function(output) { console.log(output)})
> { api_key: 'f8f4881cc4bf41eabb48e9f499293e5cde1c62f9',
  id: 4,
  links: { self: '/v1/instances/test/api_keys/4/' } }

> syncano.ApiKeys.list().then(function(output) { console.log(output)})
> {}
```

**Comment by gietek** [comment]
Works fine for me. You can check this in test/browser/ page.
Probably you are trying to call list() before create() command has succeeded.
If so, please close the the ticket. If not, please provide full code.

**Comment by mkucharz** [comment]
I've sent you full code on Slack.

**Comment by gietek** [comment]
The list isn't empty - it just displays empty object on node console. If you try to call 
```
output.length
```
or
```
output.at(0)
```
you'll see that it actually contains data
