### ISSUE TITLE
Add Tirgger traces method

### ISSUE THREAD

**Issue by hwesol13** [Syncano/syncano4-js#4]
There is no possibility to list or get a trace of trigger.
GET /v1/instances/{instance_name}/triggers/{lookup_trigger_id}/traces/
GET /v1/instances/{instance_name}/triggers/{lookup_trigger_id}/traces/{pk}/

**Comment by gietek** [comment]
Created new methods: Triggers.traces and Triggers.trace and tests in examples/browser/
